apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-server-prod
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'    
    chart: nginx                     
    targetRevision: 18.3.5                  
    helm:
      values: |
        service:
          type: LoadBalancer
        replicaCount: 5
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-nginx-server-prod                 
  syncPolicy:
    automated:
      prune: true                             
      selfHeal: true 
